package fr.guig33k.repertoire.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

@Entity
//@Table(name = "contact")
public class Contact {

	// An autogenerated id (unique for each user in the db)
	  @Id
	  @GeneratedValue(strategy = GenerationType.AUTO)
	  private long id;
	  
	  @NotNull
	  private String prenom;

	  @NotNull
	  private String nom;

	  @NotNull
	  private String email;
	  
	  @NotNull
	  private String adresse;
	  
	  // Public methods
	  
	  public Contact() { }

	  public Contact(long id) { 
	    this.id = id;
	  }
	  
	  public Contact(String prenom, String nom, String email, String adresse) {
		  this.prenom = prenom;
		  this.nom = nom;
		  this.email = email;
		  this.adresse = adresse;
	  }

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getPrenom() {
		return prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAdresse() {
		return adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	
}
